### ISSUE TITLE
stone chunks?

### ISSUE THREAD

**Issue by eksynn** [IndeedPlusPlus/RimworldStackXXL#11]
does this mod work with stone chunks as well?
if not, any way to add stone chunks to the list of stackable things too?

the file that governs this might be Various_Stone.xml in the ThingDefs_Misc folder, under ChunkBase
i tried to mod that core file myself but now stones won't even spawn lol

**Comment by jiahuif** [comment]
It is a known bad idea to try to stack "naturally unstackable" items like chunks, bodies, weapons, or artifacts. I saw some related discussion somewhere but I am unable to find them right now. 

Still, I believe even if it is possible, it is not the responsibility of a stack size modification mod.

**Comment by eksynn** [comment]
but they're stone chunks.. i can stack chunks up in real life
i mean i can stack bodies and weapons too but, just stone chunks would be cool xD

"I believe even if it is possible, it is not the responsibility of a stack size modification mod."
• but it would be _creating_ stacks. out of actually naturally stackable elements that would kinda make sense to be stackable. but alright, thank you for responding ^^

... on that note, any chance of making a _separate_ mod for stackable stone chunks? xD (as i said, i tried to make one myself but i failed so hard that the stone chunks completely disappeared ( ╥ ᴗ╥))
