### ISSUE TITLE
Without changing any settings, my stacks being truncated upon loading a save game.

### ISSUE THREAD

**Issue by camk16** [IndeedPlusPlus/RimworldStackXXL#3]
I'm having a problem with my stacks getting truncated.

Sometimes, without changing any of the settings, I'll load a save and for some reason unkown to me, my stacks are truncated. Is there any reason why this might be happening?

I'd be happy to provide any relevant information you might want/need for troubleshooting.

Thanks.

**Comment by camk16** [comment]
Solved, I think.

I changed the setting "Others (Single)" from "Not Changed" to "XL". I don't understand why being set as "Not Changed" was suddenly causing my raw food/steel stacks to be truncated, but that does seem to be what happened.

**Comment by jiahuif** [comment]
Actually, the warning is given already. If you decrease the stack size, either by change the value or choose another category, the stacks will be truncated. It won't crash your game though, you can spawn items with dev tool for compensation.
